#pragma once

typedef enum ItemType {
  ITEM_INVALID = -1,
  ITEM_SPEED_UP = 0,
  ITEM_FIRE_RATE_UP,
  ITEM_TURN_SPEED_UP,
  ITEM_DAMAGE_UP,
  // ITEM_ACCURACY_UP,
  ITEM_SHOT_SPEED_UP,
  ITEM_SHOT_COUNT_UP,
  ITEM_SHOT_KB_UP,
  ITEM_PIERCE_UP,
  ITEM_MAGNETISM_UP,
  ITEM_HOMING_POWER,
  ITEM_SIGHT_UP,
  ITEM_MAX_HP_UP,
  ITEM_REGEN_UP,
  ITEM_CONTACT_DAMAGE_UP,
  ITEM_CREATIVITY_UP,
  ITEM_SPLIT_SHOT,
  ITEM_FROST_SHOT,
  ITEM_ORBITALS_UP,
  ITEM_SPIKE_SHIELD,
  ITEM_FLAME_SHOT,
  ITEM_SPLASH_DAMAGE,
  ITEM_COUNT
} ItemType;

extern const char* const item_strs[];