#include "item_types.h"

const char* const item_strs[] = {
    [ITEM_SPEED_UP] = "Speed",
    [ITEM_FIRE_RATE_UP] = "FR",
    [ITEM_TURN_SPEED_UP] = "RotAcc",
    [ITEM_DAMAGE_UP] = "SDmg",  //    [ITEM_ACCURACY_UP] = "Acc",
    [ITEM_SHOT_SPEED_UP] = "SSpeed",
    [ITEM_SHOT_COUNT_UP] = "SCount",
    [ITEM_SHOT_KB_UP] = "KB",
    [ITEM_PIERCE_UP] = "Pierce",
    [ITEM_MAGNETISM_UP] = "Magnet",
    [ITEM_HOMING_POWER] = "Homing",
    [ITEM_SIGHT_UP] = "Sight",
    [ITEM_MAX_HP_UP] = "MaxHp",
    [ITEM_REGEN_UP] = "Regen",
    [ITEM_CONTACT_DAMAGE_UP] = "CDmg",
    [ITEM_CREATIVITY_UP] = "Create",
    [ITEM_SPLIT_SHOT] = "Split",
    [ITEM_FROST_SHOT] = "Frost",
    [ITEM_ORBITALS_UP] = "Orbit",
    [ITEM_SPIKE_SHIELD] = "Spike",
    [ITEM_FLAME_SHOT] = "Flame",
    [ITEM_SPLASH_DAMAGE] = "Splash Damage",
    [ITEM_COUNT] = "ERROR",
};